FROM node:20
RUN apt-get update && apt-get install -y build-essential python3 git curl wget vim

WORKDIR /app
COPY scenario-b/app/package*.json ./
RUN npm install
COPY scenario-b/app/ .

EXPOSE 3000
CMD ["node", "server.js"]
